apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lab-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lab
  template:
    metadata:
      labels:
        app: nginx-lab
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: main.conf
            - name: html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: config-volume
          configMap:
            name: nginx-lab-config
        - name: html-volume
          configMap:
            name: nginx-lab-config