apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: lab-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lab # חייב להתאים לסרביס
  template:
    metadata:
      labels:
        app: nginx-lab
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            # load config as single file from destination folder
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: main.conf
            # טעינת ה-HTML כקובץ בודד
            # load HTML as single file from destination folder
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-lab-config
        - name: nginx-html
          configMap:
            name: nginx-lab-config