apiVersion: v1
kind: Service
metadata:
  name: nginx-example-svc
spec:
  selector:
    app: nginx-example
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
