apiVersion: v1
kind: Service
metadata:
  name: nginx-lab
  namespace: lab-security
spec:
  selector:
    app: nginx-lab
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
